In [2]:
import numpy as np

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('E:\\Python\Data\\1000 educational data_final.csv')

In [5]:
df.head()

math_score  science_score  reading_score  final_marks  employment_status  \
0       68.53          52.05          37.35       323.10                  0   
1       43.47          23.83          23.88       292.62                  0   
2       61.05          64.08          50.39       325.49                  1   
3       62.65          50.01          26.38       428.42                  0   
4       58.67          30.86          51.66       327.54                  0   

    religion geographic_info teaching_method teaching_materials  \
0  Christian           Rural  constructivist             No use   
1   Buddhist           Urban          modern             No use   
2   Buddhist           Urban  constructivist   digital resource   
3     Others           Rural     traditional           hands-on   
4   Buddhist           Urban  constructivist             No use   

   technology_use  passed  attendance_rate  class_participation  \
0               0       1               70                    2   
1               0       1               44                    9   
2               1       1               79                    8   
3               1       1               43                    2   
4               0       1               90                    3   

   assignment_completed  presentation_marks  group_work  field_work  \
0                     0                   4           2          13   
1                     3                   8           1           7   
2                     8                   5           8          17   
3                     6                   7           7           6   
4                     4                  10           3           2   

   graduation_status  scholarship  online_learning  
0                  1            1                0  
1                  0            1                0  
2                  1            0                1  
3                  0            0                0  
4                  1            0                1

In [6]:
df.info

<bound method DataFrame.info of      math_score  science_score  reading_score  final_marks  employment_status  \
0         68.53          52.05          37.35       323.10                  0   
1         43.47          23.83          23.88       292.62                  0   
2         61.05          64.08          50.39       325.49                  1   
3         62.65          50.01          26.38       428.42                  0   
4         58.67          30.86          51.66       327.54                  0   
..          ...            ...            ...          ...                ...   
995       55.46          55.98          60.31       347.90                  0   
996       63.45          62.00          29.93       300.11                  1   
997       44.20          54.68          47.80       374.07                  0   
998       64.60          64.39          17.29       425.04                  1   
999       39.88          60.49          77.12       335.81                  0

In [7]:
df.describe()

math_score  science_score  reading_score  final_marks  \
count  1000.000000    1000.000000    1000.000000  1000.000000   
mean     54.689740      50.731780      49.941560   350.912240   
std      15.297087      12.041751      20.056374    52.255651   
min      10.000000      10.000000       1.000000   183.850000   
25%      44.537500      42.715000      35.792500   316.450000   
50%      54.930000      51.035000      50.615000   350.105000   
75%      65.725000      58.782500      63.855000   386.225000   
max      95.000000      85.110000     100.000000   500.000000   

       employment_status  technology_use       passed  attendance_rate  \
count        1000.000000     1000.000000  1000.000000      1000.000000   
mean            0.477000        0.495000     0.968000        70.792000   
std             0.499721        0.500225     0.176088        17.537397   
min             0.000000        0.000000     0.000000        40.000000   
25%             0.000000        0.000000     1.000000        55.750000   
50%             0.000000        0.000000     1.000000        71.000000   
75%             1.000000        1.000000     1.000000        86.000000   
max             1.000000        1.000000     1.000000       100.000000   

       class_participation  assignment_completed  presentation_marks  \
count          1000.000000           1000.000000         1000.000000   
mean              5.275000              5.266000            5.040000   
std               3.177967              3.145018            3.160124   
min               0.000000              0.000000            0.000000   
25%               2.000000              3.000000            2.000000   
50%               5.000000              5.000000            5.000000   
75%               8.000000              8.000000            8.000000   
max              10.000000             10.000000           10.000000   

        group_work   field_work  graduation_status  scholarship  \
count  1000.000000  1000.000000        1000.000000  1000.000000   
mean      4.996000    10.294000           0.512000     0.543000   
std       3.093793     6.048483           0.500106     0.498397   
min       0.000000     0.000000           0.000000     0.000000   
25%       2.000000     5.000000           0.000000     0.000000   
50%       5.000000    10.000000           1.000000     1.000000   
75%       8.000000    15.000000           1.000000     1.000000   
max      10.000000    20.000000           1.000000     1.000000   

       online_learning  
count      1000.000000  
mean          0.486000  
std           0.500054  
min           0.000000  
25%           0.000000  
50%           0.000000  
75%           1.000000  
max           1.000000

In [8]:
df.columns

Index(['math_score', 'science_score', 'reading_score', 'final_marks',
       'employment_status', 'religion', 'geographic_info', 'teaching_method',
       'teaching_materials', 'technology_use', 'passed', 'attendance_rate',
       'class_participation', 'assignment_completed', 'presentation_marks',
       'group_work', 'field_work', 'graduation_status', 'scholarship',
       'online_learning'],
      dtype='object')

In [9]:
df['passed'].view

<bound method Series.view of 0      1
1      1
2      1
3      1
4      1
      ..
995    1
996    1
997    1
998    1
999    1
Name: passed, Length: 1000, dtype: int64>

In [10]:
df['passed'].head(100)

0     1
1     1
2     1
3     1
4     1
     ..
95    1
96    1
97    1
98    0
99    1
Name: passed, Length: 100, dtype: int64

In [11]:
df['passed'].tail(100)

900    1
901    1
902    1
903    1
904    1
      ..
995    1
996    1
997    1
998    1
999    1
Name: passed, Length: 100, dtype: int64

In [12]:
df['passed'].unique()

array([1, 0], dtype=int64)

In [17]:
df[df['passed'] == 0].value_counts()

math_score  science_score  reading_score  final_marks  employment_status  religion   geographic_info  teaching_method  teaching_materials  technology_use  passed  attendance_rate  class_participation  assignment_completed  presentation_marks  group_work  field_work  graduation_status  scholarship  online_learning
22.46       48.85          85.29          211.74       0                  Buddhist   Rural            traditional      No use              0               0       62               4                    7                     0                   10          2           0                  0            1                  1
29.15       45.65          35.81          213.41       0                  Others     Rural            modern           hands-on            1               0       86               1                    4                     4                   4           12          0                  1            1                  1
80.42       41.57          67.04          236

In [18]:
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold, RepeatedKFold
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import numpy as np
import pandas as pd

In [19]:
X = df[['final_marks']]
y = df['passed']

X.shape, y.shape

((1000, 1), (1000,))

In [22]:
## Preprocessing for Numerical Data 

numeric_transformer = Pipeline(steps=[('scaler', StandardScaler())])

## Define the Models 

In [23]:
svm_model = Pipeline(steps = [('preprocessor', numeric_transformer), ('classifier', SVC())])
logistic_model = Pipeline(steps = [('preprocessor', numeric_transformer), ('classifier', LogisticRegression())])

## Splitting the data into training and testing sets

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(800, 1) (200, 1) (800,) (200,)


## Train and Evaluate SVM Model

In [26]:
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)  # Predicting the test set results
svm_accuracy = accuracy_score(y_test, y_pred_svm) # Calculating the accuracy of the model
print(y_pred_svm)
print(svm_accuracy)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
1.0


## Train and Evaluation Logistic Regression Model 

In [27]:
logistic_model.fit(X_train, y_train)
y_pred_logistic = logistic_model.predict(X_test)  # Predicting the test set results
logistic_accuracy = accuracy_score(y_test, y_pred_logistic) # Calculating the accuracy of the model 
print(y_pred_logistic)
print(logistic_accuracy)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
0.995


## Cross Validation

### Performing k-fold cross validation

In [28]:
svm_score = cross_val_score(svm_model, X, y, cv=10)
print(svm_score)

[0.99 1.   1.   1.   1.   1.   0.99 1.   1.   1.  ]


In [29]:
svm_mean_score = np.mean(svm_score)
svm_mean_score

0.998

In [30]:
logistic_score = cross_val_score(logistic_model, X, y, cv = 10)
logistic_score

array([0.99, 0.98, 0.98, 1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 0.98])

In [32]:
logistic_mean_score = np.mean(logistic_score)
logistic_mean_score

0.993

## Stratified KFold Cross Validation

In [33]:
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
svm_score_skf = cross_val_score(svm_model, X, y, cv=skf)
svm_mean_score_skf = np.mean(svm_score_skf)
print(svm_score_skf)
print(svm_mean_score_skf)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
1.0


In [34]:
skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=1)
logistic_score_skf = cross_val_score(logistic_model, X, y, cv=skf)
logistic_mean_score_skf = np.mean(logistic_score_skf)
print(logistic_score_skf)
print(logistic_mean_score_skf)

[0.98 1.   1.   1.   0.99 0.99 0.99 0.98 0.99 1.  ]
0.992


## Repeated KFold Cross Validation

In [35]:
rkf = RepeatedKFold(n_splits=10, n_repeats=10, random_state=42)
svm_score_rkf = cross_val_score(svm_model, X, y, cv=rkf)
svm_mean_score_rkf = np.mean(svm_score_rkf)
print(svm_score_rkf)
print(svm_mean_score_rkf)

[1.   1.   1.   1.   0.99 1.   1.   1.   1.   1.   1.   1.   1.   1.
 1.   1.   1.   1.   0.99 1.   1.   1.   1.   1.   0.99 1.   1.   1.
 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
 1.   1.   1.   1.   1.   0.99 1.   1.   1.   1.   1.   0.99 0.99 1.
 0.99 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   0.98 1.
 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
 1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.   1.
 1.   1.  ]
0.9991


In [36]:
rkf = RepeatedKFold(n_splits=10, n_repeats=10, random_state=42)
logistic_score_rkf = cross_val_score(logistic_model, X, y, cv=rkf)
logistic_mean_score_rkf = np.mean(logistic_score_rkf)
print(logistic_score_rkf)
print(logistic_mean_score_rkf)

[0.98 1.   0.99 1.   1.   0.96 1.   1.   0.98 1.   1.   1.   0.98 1.
 0.98 0.99 0.99 0.99 0.99 1.   1.   1.   1.   1.   1.   0.99 0.99 1.
 0.97 0.98 0.98 1.   0.99 1.   0.99 0.97 1.   1.   1.   1.   0.99 0.98
 1.   0.98 1.   1.   0.99 1.   0.99 0.99 1.   0.99 1.   0.96 1.   1.
 0.97 1.   0.99 1.   0.98 1.   0.99 1.   0.97 0.99 1.   1.   1.   0.99
 1.   0.99 0.98 1.   1.   0.99 0.99 0.98 1.   0.99 0.99 0.99 0.99 0.99
 1.   1.   0.97 1.   0.99 1.   0.99 0.99 1.   1.   1.   0.99 1.   0.95
 0.99 1.  ]
0.9919


## Compiling all into a DataFrame 

In [38]:
results = pd.DataFrame({'Method':
    ['Train-Test Split', 
     'K-Fold Cross Validation',
     'StratifiedKFold Cross Validation',
     'RepeatedKFold Cross Validation'],
    'SVM Accuracy': [
        svm_accuracy,
        svm_mean_score,
        svm_mean_score_skf,
        svm_mean_score_rkf
    ],
    'Logistic Regression Accuracy': [
        logistic_accuracy, 
        logistic_mean_score,
        logistic_mean_score_skf,
        logistic_mean_score_rkf
    ]})

print(results)

                             Method  SVM Accuracy  \
0                  Train-Test Split        1.0000   
1           K-Fold Cross Validation        0.9980   
2  StratifiedKFold Cross Validation        1.0000   
3    RepeatedKFold Cross Validation        0.9991   

   Logistic Regression Accuracy  
0                        0.9950  
1                        0.9930  
2                        0.9920  
3                        0.9919  


## Leave One Out Cross Validation (LOOCV)

In [40]:
from sklearn.model_selection import LeaveOneOut

In [43]:
loo =LeaveOneOut()
svm_score_loo = cross_val_score(svm_model, X, y, cv = loo)
svm_mean_score_loo = np.mean(svm_score_loo)
print(svm_score_loo)
print(svm_mean_score_loo)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [45]:
#For logistic Regression
loo =LeaveOneOut()
logistic_score_loo = cross_val_score(logistic_model, X, y, cv = loo)
logistic_mean_score_loo = np.mean(logistic_score_loo)
print(logistic_score_loo)
print(logistic_mean_score_loo)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.

In [48]:
X.iloc[100], y.iloc[100]

(final_marks    385.57
 Name: 100, dtype: float64,
 1)

====================================================

In [49]:
from sklearn.model_selection import LeaveOneOut
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import numpy as np 
import pandas as pd

In [50]:
file = 'E:\\Python\Data\\1000 educational data_final.csv'
df = pd.read_csv(file)
df.head()

math_score  science_score  reading_score  final_marks  employment_status  \
0       68.53          52.05          37.35       323.10                  0   
1       43.47          23.83          23.88       292.62                  0   
2       61.05          64.08          50.39       325.49                  1   
3       62.65          50.01          26.38       428.42                  0   
4       58.67          30.86          51.66       327.54                  0   

    religion geographic_info teaching_method teaching_materials  \
0  Christian           Rural  constructivist             No use   
1   Buddhist           Urban          modern             No use   
2   Buddhist           Urban  constructivist   digital resource   
3     Others           Rural     traditional           hands-on   
4   Buddhist           Urban  constructivist             No use   

   technology_use  passed  attendance_rate  class_participation  \
0               0       1               70                    2   
1               0       1               44                    9   
2               1       1               79                    8   
3               1       1               43                    2   
4               0       1               90                    3   

   assignment_completed  presentation_marks  group_work  field_work  \
0                     0                   4           2          13   
1                     3                   8           1           7   
2                     8                   5           8          17   
3                     6                   7           7           6   
4                     4                  10           3           2   

   graduation_status  scholarship  online_learning  
0                  1            1                0  
1                  0            1                0  
2                  1            0                1  
3                  0            0                0  
4                  1            0                1

In [52]:
X = df[['final_marks', 'math_score', 'reading_score', 'science_score']]
y = df['passed']
X.shape, y.shape

((1000, 4), (1000,))

In [53]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

## Intializing the One Leave Out Cross Validation

In [54]:
loo = LeaveOneOut()
loo

LeaveOneOut()

In [66]:
svm_accuracy = []
logistic_accuracy = []

## Performing LOOCV

In [91]:
for train_index, test_index in loo.split(X_scaled):
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y[train_index], y[test_index] 

In [92]:
print(train_index)

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [93]:
test_index

array([999])

In [94]:
X_test

array([[-0.28915144, -0.96862562,  1.35578045,  0.81077104]])

## Train and Evaluate Models 

In [106]:
for train_index, test_index in loo.split(X_scaled):
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y[train_index], y[test_index] 
    svm_model = SVC() 
    svm_model.fit(X_train, y_train) 
    y_pred_svm = svm_model.predict(X_test)
    svm_accuracy.append(accuracy_score(y_test, y_pred_svm))
print(svm_accuracy)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,

In [108]:
svm_mean_score = np.mean(svm_accuracy)
svm_mean_score

0.9901283316880553

In [107]:
for train_index, test_index in loo.split(X_scaled):
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y[train_index], y[test_index] 
    logistic_model = LogisticRegression()
    logistic_model.fit(X_train, y_train) 
    y_pred_logistic = logistic_model.predict(X_test)
    logistic_accuracy.append(accuracy_score(y_test, y_pred_logistic))
print(logistic_accuracy)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,

In [111]:
logistic_mean_score = np.mean(logistic_accuracy)
logistic_mean_score

0.9940119760479041

In [79]:
from sklearn.model_selection import LeaveOneOut
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

# Load the dataset
file = 'E:\\Python\Data\\1000 educational data_final.csv'
df = pd.read_csv(file)

# Define the features and target variable
X = df[['final_marks', 'math_score', 'reading_score', 'science_score']]
y = df['passed']

# Scale the numerical data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Initialize LeaveOneOut cross-validator
loo = LeaveOneOut()

# Lists to store accuracy for each iteration
svm_accuracies = []
logistic_accuracies = []

# Perform LOOCV
for train_index, test_index in loo.split(X_scaled):
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # Train and evaluate SVM
    svm_model = SVC()
    svm_model.fit(X_train, y_train)
    y_pred_svm = svm_model.predict(X_test)
    svm_accuracies.append(accuracy_score(y_test, y_pred_svm))
    
    # Train and evaluate Logistic Regression
    logistic_model = LogisticRegression(max_iter=1000)
    logistic_model.fit(X_train, y_train)
    y_pred_logistic = logistic_model.predict(X_test)
    logistic_accuracies.append(accuracy_score(y_test, y_pred_logistic))

# Calculate mean accuracy
svm_mean_accuracy = np.mean(svm_accuracies)
logistic_mean_accuracy = np.mean(logistic_accuracies)

print("SVM Mean Accuracy:", svm_mean_accuracy)
print("Logistic Regression Mean Accuracy:", logistic_mean_accuracy)


SVM Mean Accuracy: 0.99
Logistic Regression Mean Accuracy: 0.994


In [81]:
X_test

array([[-0.28915144, -0.96862562,  1.35578045,  0.81077104]])

In [83]:
test_index

array([999])

# Choosing Specific Test Value 

In [113]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

# Load the dataset
file = 'E:\\Python\\Data\\1000 educational data_final.csv'  # Update the path as necessary
df = pd.read_csv(file)

# Define the features and target variable
X = df[['final_marks', 'math_score', 'reading_score', 'science_score']]
y = df['passed']

# Scale the numerical data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Specify the index of the test sample
test_index = 0  # Replace with the index you want to test

# Split the data
X_test = X_scaled[test_index].reshape(1, -1)
y_test = y.iloc[test_index]

X_train = np.delete(X_scaled, test_index, axis=0)
y_train = y.drop(index=test_index)

# Train and evaluate SVM
svm_model = SVC()
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)
svm_accuracy = accuracy_score([y_test], y_pred_svm)

# Train and evaluate Logistic Regression
logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train, y_train)
y_pred_logistic = logistic_model.predict(X_test)
logistic_accuracy = accuracy_score([y_test], y_pred_logistic)

print("SVM Accuracy for test sample:", svm_accuracy)
print("Logistic Regression Accuracy for test sample:", logistic_accuracy)


SVM Accuracy for test sample: 1.0
Logistic Regression Accuracy for test sample: 1.0


In [114]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

# Load the dataset
file = 'E:\\Python\\Data\\1000 educational data_final.csv'  # Update the path as necessary
df = pd.read_csv(file)

# Define the features and target variable
X = df[['final_marks', 'math_score', 'reading_score', 'science_score']]
y = df['passed']

# Scale the numerical data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Specify the index of the test sample
test_index = 2  # Replace with the index you want to test

# Split the data
X_test = X_scaled[test_index].reshape(1, -1)
y_test = y.iloc[test_index]

X_train = np.delete(X_scaled, test_index, axis=0)
y_train = y.drop(index=test_index)

# Train and evaluate SVM
svm_model = SVC()
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)
svm_accuracy = accuracy_score([y_test], y_pred_svm)

# Train and evaluate Logistic Regression
logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train, y_train)
y_pred_logistic = logistic_model.predict(X_test)
logistic_accuracy = accuracy_score([y_test], y_pred_logistic)

print("SVM Accuracy for test sample:", svm_accuracy)
print("Logistic Regression Accuracy for test sample:", logistic_accuracy)


SVM Accuracy for test sample: 1.0
Logistic Regression Accuracy for test sample: 1.0


In [115]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

# Load the dataset
file = 'E:\\Python\\Data\\1000 educational data_final.csv'  # Update the path as necessary
df = pd.read_csv(file)

# Define the features and target variable
X = df[['final_marks', 'math_score', 'reading_score', 'science_score']]
y = df['passed']

# Scale the numerical data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Specify the index of the test sample
test_index = 999  # Replace with the index you want to test

# Split the data
X_test = X_scaled[test_index].reshape(1, -1)
y_test = y.iloc[test_index]

X_train = np.delete(X_scaled, test_index, axis=0)
y_train = y.drop(index=test_index)

# Train and evaluate SVM
svm_model = SVC()
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)
svm_accuracy = accuracy_score([y_test], y_pred_svm)

# Train and evaluate Logistic Regression
logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train, y_train)
y_pred_logistic = logistic_model.predict(X_test)
logistic_accuracy = accuracy_score([y_test], y_pred_logistic)

print("SVM Accuracy for test sample:", svm_accuracy)
print("Logistic Regression Accuracy for test sample:", logistic_accuracy)


SVM Accuracy for test sample: 1.0
Logistic Regression Accuracy for test sample: 1.0


In [118]:
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler
import numpy as np
import pandas as pd

# Load the dataset
file = 'E:\\Python\\Data\\1000 educational data_final.csv'  # Update the path as necessary
df = pd.read_csv(file)

# Define the features and target variable
X = df[['final_marks', 'math_score', 'reading_score', 'science_score']]
y = df['passed']

# Scale the numerical data
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Specify the index of the test sample
test_index = 998  # Replace with the index you want to test

# Split the data
X_test = X_scaled[test_index].reshape(1, -1)
y_test = y.iloc[test_index]

X_train = np.delete(X_scaled, test_index, axis=0)
y_train = y.drop(index=test_index)

# Train and evaluate SVM
svm_model = SVC()
svm_model.fit(X_train, y_train)
y_pred_svm = svm_model.predict(X_test)
svm_accuracy = accuracy_score([y_test], y_pred_svm)

# Train and evaluate Logistic Regression
logistic_model = LogisticRegression(max_iter=1000)
logistic_model.fit(X_train, y_train)
y_pred_logistic = logistic_model.predict(X_test)
logistic_accuracy = accuracy_score([y_test], y_pred_logistic)

print("SVM Accuracy for test sample:", svm_accuracy)
print("Logistic Regression Accuracy for test sample:", logistic_accuracy)


SVM Accuracy for test sample: 1.0
Logistic Regression Accuracy for test sample: 1.0
